import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import { GitHubLogoIcon } from "@radix-ui/react-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <header className="flex items-center justify-between py-4 px-16 sticky top-0 z-50 backdrop-blur bg-opacity-5">
          <Link href="/">Z0-Share </Link>
          <Link href="https://github.com/falcon-Z/z0-share" target="_blank">
            <GitHubLogoIcon className="w-6 h-6 bg-neutral-950" />
          </Link>
        </header>
        <main className="grid place-items-center min-h-screen m-1 lg:p-4 ">
          {children}
        </main>
      </body>
    </html>
  );
}
