import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <header className="flex items-center justify-between p-4">
          <Link href="/">Z0-Share </Link>
        </header>
        <main className="grid place-items-center min-h-screen m-1 lg:p-4 ">
          {children}
        </main>
      </body>
    </html>
  );
}
